name: etar_q
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.3
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  firebase_ui_auth: ^1.10.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_ui_localizations: ^1.8.0
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  firebase_ui_firestore: ^1.5.14
  dropdown_button2: ^2.3.9
  flutter_launcher_icons: ^0.13.1
  intl: ^0.18.1
  flutter_layout_grid: ^2.0.5
  flutter_rating_bar: ^4.0.1
  riverpod_annotation: ^2.3.3
  excel: ^4.0.0
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf