// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi-02tmfUsD2asFZ43dF1T3KJ9SbtF450',
    appId: '1:211744724721:web:7edbc4db63b17e24e0fb50',
    messagingSenderId: '211744724721',
    projectId: 'faker-andrea',
    authDomain: 'faker-andrea.firebaseapp.com',
    storageBucket: 'faker-andrea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCExVQp3sXQ3qaxl8WCwtm5vRocmnNQqng',
    appId: '1:211744724721:android:a45f91e1ec8cf8cee0fb50',
    messagingSenderId: '211744724721',
    projectId: 'faker-andrea',
    storageBucket: 'faker-andrea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjqWUKfP6mlql_xgoHkx-QGLcq3qTMCgU',
    appId: '1:211744724721:ios:87b5f29b2920bcb1e0fb50',
    messagingSenderId: '211744724721',
    projectId: 'faker-andrea',
    storageBucket: 'faker-andrea.appspot.com',
    iosClientId: '211744724721-20ht6kop2fn2ijic9n750bgpnlsng257.apps.googleusercontent.com',
    iosBundleId: 'com.example.etarq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjqWUKfP6mlql_xgoHkx-QGLcq3qTMCgU',
    appId: '1:211744724721:ios:2e0d93e645b36f48e0fb50',
    messagingSenderId: '211744724721',
    projectId: 'faker-andrea',
    storageBucket: 'faker-andrea.appspot.com',
    iosClientId: '211744724721-6acia27ie2245rmjmro0cc26nl2is36b.apps.googleusercontent.com',
    iosBundleId: 'com.example.etarq.RunnerTests',
  );
}
